project_id = "nxtfugcmatkiqjzxucgh"

[functions.get-service-role-key]
verify_jwt = false

[functions.n8n-send-recommendations]
verify_jwt = false

[functions.n8n-yara-chat]
verify_jwt = false

[functions.twilio-whatsapp-webhook]
verify_jwt = false

[functions.cleanup-past-events]
verify_jwt = false

[functions.yara-ai-chat]
verify_jwt = false

[functions.send-whatsapp-recommendations]
verify_jwt = false

[functions.yara-api]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.generate-synonyms]
verify_jwt = false

[functions.semantic-event-search]
verify_jwt = false

[functions.archive-expired-events]
verify_jwt = false

[functions.send-followup-messages]
verify_jwt = false

[functions.send-24h-followup]
verify_jwt = false

[functions.send-manual-whatsapp]
verify_jwt = false
