project_id = "nxtfugcmatkiqjzxucgh"

[functions.get-service-role-key]
verify_jwt = false

[functions.twilio-whatsapp-webhook]
verify_jwt = false

[functions.cleanup-past-events]
verify_jwt = false

[functions.yara-ai-chat]
verify_jwt = false

[functions.send-whatsapp-recommendations]
verify_jwt = false

[functions.scan-instagram-events]
verify_jwt = false